[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "dotnet", "python"]

[env]
_.file = ".env"

[[watch_files]]
patterns = [".env", ".envrc"]
run = "mise set"

[tools]
usage = "latest"
